version: '3.7'
services:
  oracle:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - ${PROMETHEUS_METRICS_PORT}:8000
    environment:
      # Required parameters
      #
      #
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      ORACLE_PRIVATE_KEY: ${ORACLE_PRIVATE_KEY}
      WS_URL_RELAY: ${WS_URL_RELAY}
      WS_URL_PARA: ${WS_URL_PARA}

      # Optional parameters
      #
      #
      ABI_PATH: ${ABI_PATH}

      TIMEOUT: ${TIMEOUT}
      WATCHDOG_DELAY: ${WATCHDOG_DELAY}

      ERA_DURATION_IN_BLOCKS: ${ERA_DURATION_IN_BLOCKS}
      ERA_DURATION_IN_SECONDS: ${ERA_DURATION_IN_SECONDS}
      INITIAL_BLOCK_NUMBER: ${INITIAL_BLOCK_NUMBER}

      SS58_FORMAT: ${SS58_FORMAT}
      TYPE_REGISTRY_PRESET: ${TYPE_REGISTRY_PRESET}
