version: '3.7'
services:
  oracle:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      WS_URL_RELAY: "wss://dev.lido.mixbytes.io/relay"
      WS_URL_PARA:  "wss://dev.lido.mixbytes.io/para"
      CONTRACT_ADDRESS: "0x746DFE0F96789e62CECeeA3CA2a9b5556b3AaD6c"
      ORACLE_PRIVATE_KEY: "0x925eda0e60dac4a29712e1f9cfe1a3f1efe4270596e46722295248428f25e6ee"
