name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: mixbytes/lido-dot-ksm-oracle
          tags: |
            type=ref,event=pr
            type=sha,prefix={{branch}}-,format=short,enable=${{ github.event_name == 'push' && !contains(github.ref, '/tags/') }}
            type=semver,pattern={{raw}}

      -
        name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}

