name: Build and deploy our dev application

on:
  push:
    branches: 
      - 'develop'

env: 
  DEPLOYMENT_MANIFEST_PATH: './manifests'
  APP: oracle1-dpl
  APP_2: oracle2-dpl
  NAMESPACE1: dev-ksm-oracle1-ns
  NAMESPACE2: dev-dot-oracle1-ns
  NAMESPACE3: dev-testnet-oracle1-ns
  NAMESPACE2_1: dev-ksm-oracle2-ns
  NAMESPACE2_2: dev-dot-oracle2-ns
  NAMESPACE2_3: dev-testnet-oracle2-ns
  TYPE_ENV: develop
  NETWORK1: kusama
  NETWORK2: polkadot
  NETWORK3: testnet
  DOCKER_IMAGE_NAME: mixbytes/lido-dot-ksm-oracle

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/develop')
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

  build-dev:
    needs: build 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ needs.build.outputs.branch == 'develop' }}
    steps:
      - name: Send telegram message on push commit
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Send telegram message on push image
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Automation message: IMAGE > ${{ env.DOCKER_IMAGE_NAME }}:latest > Build and Push to Dockerhub Successfully!

  # deploy-dev:
  #   needs: build-dev 
  #   runs-on: ubuntu-latest
  #   if: ${{ needs.build.outputs.branch == 'develop' }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1

  #     - name: Get config kubernetes
  #       uses: actions-hub/kubectl@master
  #       env:
  #         KUBE_CONFIG: ${{ secrets.TEST_KUBE_CONFIG_DATA }}

  #     - name: Deployment apply to kubernetes
  #       uses: actions-hub/kubectl@master
  #       with:
  #         args: apply -f ${{ env.DEPLOYMENT_MANIFEST_PATH }}/${{ env.TYPE_ENV }}/${{ env.NETWORK1 }}/deployment.yaml --namespace=${{ env.NAMESPACE1 }}

  #     - name: Deployment rollout restart to kubernetes
  #       uses: actions-hub/kubectl@master
  #       with:
  #         args: rollout restart deployment ${{ env.APP }} --namespace=${{ env.NAMESPACE1 }}

  #     - name: Send telegram message on deploy to DEV Kubernetes
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_TO }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         message: |
  #           ✅ Automation message: IMAGE > ${{ env.DOCKER_IMAGE_NAME }}:latest > Deploy to DEV Kubernetes ${{ env.NETWORK1 }} Successfully!

  #     - name: Deployment apply to kubernetes
  #       uses: actions-hub/kubectl@master
  #       with:
  #         args: apply -f ${{ env.DEPLOYMENT_MANIFEST_PATH }}/${{ env.TYPE_ENV }}/${{ env.NETWORK2 }}/deployment.yaml --namespace=${{ env.NAMESPACE2 }}

  #     - name: Deployment rollout restart to kubernetes
  #       uses: actions-hub/kubectl@master
  #       with:
  #         args: rollout restart deployment ${{ env.APP }} --namespace=${{ env.NAMESPACE2 }}

  #     - name: Send telegram message on deploy to DEV Kubernetes
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_TO }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         message: |
  #           ✅ Automation message: IMAGE > ${{ env.DOCKER_IMAGE_NAME }}:latest > Deploy to DEV Kubernetes ${{ env.NETWORK2 }} Successfully!

  #     - name: Deployment apply to kubernetes
  #       uses: actions-hub/kubectl@master
  #       with:
  #         args: apply -f ${{ env.DEPLOYMENT_MANIFEST_PATH }}/${{ env.TYPE_ENV }}/${{ env.NETWORK3 }}/deployment.yaml --namespace=${{ env.NAMESPACE3 }}

  #     - name: Deployment rollout restart to kubernetes
  #       uses: actions-hub/kubectl@master
  #       with:
  #         args: rollout restart deployment ${{ env.APP }} --namespace=${{ env.NAMESPACE3 }}

  #     - name: Send telegram message on deploy to DEV Kubernetes
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_TO }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         message: |
  #           ✅ Automation message: IMAGE > ${{ env.DOCKER_IMAGE_NAME }}:latest > Deploy to DEV Kubernetes ${{ env.NETWORK3 }} Successfully!